name: Laravel Code Linting

on:
  workflow_dispatch:       
  push:
    branches:
      - testing            
  pull_request:
    branches:
      - testing           

jobs:
  lint:
    name: PHP CodeSniffer Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2                
          extensions: mbstring, xml
          tools: phpcs
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist
        working-directory: src/Dashboard-PLN

      - name: Run PHP_CodeSniffer (PSR-12)
        run: vendor/bin/phpcs --standard=PSR12 app/ routes/ tests/
        working-directory: src/Dashboard-PLN
