name: Laravel Auto Linting (Branch Testing)

on:
  push:
    branches: [testing]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/testing'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        working-directory: src/Dashboard-PLN
        run: composer install --no-progress --prefer-dist

      - name: Run Laravel Pint
        working-directory: src/Dashboard-PLN
        run: |
          composer require laravel/pint --dev
          vendor/bin/pint app/

      - name: Run PHPStan
        working-directory: src/Dashboard-PLN
        run: |
          composer require phpstan/phpstan --dev
          vendor/bin/phpstan analyse app --level=max

      - name: Run PHP_CodeSniffer
        working-directory: src/Dashboard-PLN
        run: |
          composer require squizlabs/php_codesniffer --dev
          vendor/bin/phpcs --standard=PSR12 app/
