name: Laravel Code Linting (with Auto Fix)

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:
  lint:
    name: Lint & Auto-fix with PHP_CodeSniffer
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/Dashboard-PLN 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml
          coverage: none

      - name: Install composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Download PHP_CodeSniffer
        run: |
          cd ../../
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
          chmod +x phpcs.phar phpcbf.phar

      - name: Run Lint Check (phpcs)
        run: |
          cd ../../
          php phpcs.phar --standard=PSR12 src/Dashboard-PLN/app src/Dashboard-PLN/routes

      - name: Auto Fix Code Style Violations (phpcbf)
        run: |
          cd ../../
          php phpcbf.phar --standard=PSR12 src/Dashboard-PLN/app src/Dashboard-PLN/routes
